### PR TITLE
implement definition of Hash#slice method

### PR DESCRIPTION
**Pull request by benolee**
* control visibility of private functions by making them static
* move FastSlice to a static global variable
* change FastSlice to be a module instead of a class
* implement replacing Hash#slice by prepending the FastSlice module
* extract core logic of both the singleton and instance methods for slice to a static function

### CODE REVIEW

**Comment by jamescook** [comment]
@benolee Can you add a test for `FastSlice.define_on_hash`? The Travis build passes on 1.9, but pretty sure it will fail once there is a test since `rb_prepend_module` is 2.x only. Compiling only generates a warning:
```
../../../../ext/fast_slice/fast_slice.c:64:3: warning: implicit declaration of function 'rb_prepend_module' is invalid in C99
      [-Wimplicit-function-declaration]
  rb_prepend_module(rb_cHash, FastSlice);
  ^
```
I'm ok with dropping support for 1.9. I was mostly just curious if it was compatible in terms of the C api.

**Comment by benolee** [comment]
I’ll definitely add tests for the ruby-facing api changes.

Prepending is a bit heavy handed. The `FastSlice.define_on_hash` method gives the user enough flexibility to determine load order.

See any reason to test the C api itself?

**Comment by jamescook** [comment]
@benolee No reason to test the C API that I can think of.

**Comment by jamescook** [comment]
Included this change in https://github.com/jamescook/fast_slice/pull/2. Thanks @benolee.

**Pull request closed without merging**
